blank_issues_enabled: false
contact_links:
  - name: Medinstech — LinKit
    url: https://www.medinstech.com/linkit/
    about: Ürün, sipariş ve diğer sorular için / For products, orders and other questions
